# Generated by Django 3.2.5 on 2023-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
