# Generated by Django 4.1.7 on 2023-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0004_alter_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contributor_permission'),
        ),
    ]
