# Generated by Django 4.1.7 on 2023-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0005_alter_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Resp', 'Responsable'), ('Contrib', 'Contributeur')], max_length=15),
        ),
    ]
