# Generated by Django 4.1.7 on 2023-03-27 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0006_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
