# Generated by Django 4.1.7 on 2023-03-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0009_alter_contributor_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Resp', 'Responsable'), ('Contrib', 'Contributeur')], default='Read', max_length=15, verbose_name='contributor_permission'),
            preserve_default=False,
        ),
    ]
