# Generated by Django 4.1.7 on 2023-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0010_alter_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('R', 'Read'), ('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], max_length=15, verbose_name='contributor_permission'),
        ),
    ]
