# Generated by Django 4.1.7 on 2023-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0012_alter_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('CR', 'Create & Read'), ('CRUD', 'Full')], default='Read', max_length=15, verbose_name='Permissions'),
        ),
    ]
