# Generated by Django 4.1.7 on 2023-04-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobticket', '0013_alter_contributor_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobticket.issue'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('CR', 'Create & Read'), ('CRUD', 'Full')], default='Create & Read', max_length=15, verbose_name='Permissions'),
        ),
    ]
